# 라이브러리 - numpy 행렬곱 (dot product) (1)

- 행렬 곱(dot product)
- => A 행렬과 B 행렬의 행렬 곱 (dot product)는 np.dot(A, B)로 나타내며, 행렬 A의 열 벡터와 B 행렬의 행 벡터가 같아야 함. 만약 같지 않다면 reshape 또는 전치행렬(transpose)등을 사용하여 형 변환을 한 후에 행렬 곱을 실행해야 함.

In [2]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]]) # 2 X 3 행렬
B = np.array([[-1, -2], [-3, -4], [-5, -6]]) # 3 X 2 행렬

# (2 X 3) dot product (3 X 2) == (2 X 2) 행렬
C = np.dot(A, B) # 행렬 곱 수행

# matrix A, B 형상 출력 => shape
print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print("C.shape ==", C.shape)
print(C)

A.shape == (2, 3) , B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


# 라이브러리 - numpy 행렬곱 (dot product) (2)

- 행렬 곱(dot product)
- => 행렬 곱은, 행렬의 원소 개수가 같아야만 계산할 수 있는 사칙연산의 한계를 벗어나
1. 행렬곱 조건을 만족하는 다양한 크기의 행렬을 연속으로 만들고
2. 행렬 곱을 연속으로 계산하면서
3. 결과값을 만들 수 있기 때문에 머신러닝과 이미지 프로세싱 분야에서 자주 사용됨.
- [예] 입력 행렬의 sahpe이 64 X 64 이고, 결과 행렬의 shape이 64 X 10 이라면, 중간에 dot product를 만족시키는 어떤 shape의 행렬이라도 가질 수 있음.
- 행렬 곱은 사용하지 않고 산술연산만 가능하다면, 입력 행렬의 64 X 64 크기를 가지는 특성값 만을 사용해야하기 때문에 다양한 특성을 갖는 필터 개발이 불가능함.

# 라이브러리 - numpy broadcast

- 행렬의 사칙연산은 기본적으로 두 개의 크기가 같은 경우에만 수행할 수 있음. 그러나 numpy에서는 크기가 다른 두 행렬간에도 사칙연산(+, -, *, /)을 할 수 있는데, 이를 브로드캐스트(broadcast)라고 지칭함.
- => 차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산

In [3]:
# scalar broadcast

A = np.array([[1, 2], [3, 4]])
b = 5

print(A + b)

[[6 7]
 [8 9]]


In [4]:
# matrix broadcast

C = np.array([[1, 2], [3, 4]])
D = np.array([4, 5])

print(C + D)

[[5 7]
 [7 9]]


# 라이브러리 - numpy 전치행렬(transpose)

- 전치행렬 (transpose)
- => 어떤 행렬의 전치행렬(transposed matrix)은 원본 행렬의 열은 행으로, 행은 열로 바꾼 것으로서, 원본 행렬을 A라고 하면 전치 행렬은 AT로 나타냄.
- 즉, 1행은 1열로 바꾸고 2행은 2열로, 3행은 3열로 바꾼 행렬을 의미

In [6]:
# 전치행렬

A = np.array([[1, 2], [3, 4], [5, 6]]) # 3 X 2 행렬

B = A.T # A의 전치행렬, 2 X 3 행렬

print("A.shape ==", A.shape, ", B,shape ==", B.shape)
print(A)
print('-----------')
print(B)

A.shape == (3, 2) , B,shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
-----------
[[1 3 5]
 [2 4 6]]


In [8]:
# vector 전치행렬

C = np.array([1, 2, 3, 4, 5]) # vector, matrix 아님
D = C.T # C는 vector이므로 transpose 안됨

E = C.reshape(1, 5) # 1 X 5 matrix
F = E.T # E의 전치행렬

print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print('-----------')
print("E.shape ==", E.shape, ", F.shape ==", F.shape)
print('-----------')
print(F)

C.shape == (5,) , D.shape == (5,)
-----------
E.shape == (1, 5) , F.shape == (5, 1)
-----------
[[1]
 [2]
 [3]
 [4]
 [5]]


# 라이브러리 - numpy 행렬 indexing / slicing

- 행렬 원소 접근 (1)
- => 행렬 원소를 명시적(explicit)으로 접근하기 위해서는 리스트(list)에서 처럼, 인덱싱 / 슬라이싱 모두 사용 가능 함.

In [15]:
# reshape

A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)

print("A.shape ==", A.shape)
print(A)

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [16]:
# indexing / slicing

print("A[0, 0] ==", A[0, 0], ", A[0][0] ==", A[0][0]) # 1행 1열
print("A[2, 1] ==", A[2, 1], ", A[2][1] ==", A[2][1]) # 3행 2열
print('-----------')
# 인덱스 0인 1행부터, 인덱스 -1 -1 = -2인 2행까지의 모든 데이터,
# 그리고 인덱스 1인 2열부터 인덱스 2-1 = 1인 2열까지의 모든 데이터
print("A[0:-1, 1:2] ==", A[0:-1, 1:2])
print('-----------')
print("A[:, 0] ==", A[:, 0]) # 모든 행 1열
print('-----------')
print("A[:, :] ==", A[:, :]) # 모든 행, 모든 열

A[0, 0] == 10 , A[0][0] == 10
A[2, 1] == 60 , A[2][1] == 60
-----------
A[0:-1, 1:2] == [[20]
 [40]]
-----------
A[:, 0] == [10 30 50]
-----------
A[:, :] == [[10 20]
 [30 40]
 [50 60]]


# 라이브러리 - numpy 행렬 indexing / slicing

- 행렬 원소 접근 (2)
- => 명시적(explicit) 인덱싱 / 슬라이싱 이외에, 행렬 모든 원소를 access 하는 경우에는 iterator 사용 가능

In [21]:
# iterator 예제

A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]]) # 2 X 4 행렬

print(A, "\n")
print("A.shape ==", A.shape, "\n")

# 행렬 A의 itrator 생성

it = np.nditer(A, flags = ['multi_index'], op_flags = ['readwrite'])

while not it.finished:
    
    idx = it.multi_index
    
    print("current value =>", A[idx])
    
    it.iternext()

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 

current value => 10
current value => 20
current value => 30
current value => 40
current value => 50
current value => 60
current value => 70
current value => 80
